### ISSUE TITLE
[EOWG] Topic and duration on overview page

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-develop-training#3]
[Current version](https://www.w3.org/WAI/training/Overview) has the number of topics and the duration after each bullet. It seems that is helpful for people to know up front.

Was that deleted from [draft revision](https://github.com/w3c/wai-develop-training/blob/master/_accessibility-training/index.md) just to cut words?

Perhaps in this case the extra words are worth the increased user knowledge on this page?

**Comment by AndrewArch** [comment]
I noticed that too Shawn - I'd certainly prefer to keep that information.

**Comment by slhenry** [comment]
reinstated
