### ISSUE TITLE
Outdated links

### ISSUE THREAD

**Issue by negi4abg** [w3c/wai-develop-training#32]
I have been looking at the "Videos of people with disabilities using the Web" section on WAI webpage. What I found is that ""Introduction to the Screen Reader video" link  seems no longer valid. It points to https://it.wisc.edu/ which is different from the original address (http://www.doit.wisc.edu/accessibility/video/intro.asp) and servs  other purpose. It seems other videos on that page pointing to University of Wisconsin -Madison resources are also outdated.
I believe at least transcripts still can be downloaded.

Even though some videos are old, they still can be useful. I hope videos are not vanished and the links can be updated.
I wrote also to the author of that resource in a hope something can be done.

**Comment by shawna-slh** [comment]
Thanks for the input @negi4abg 
The WAI resource is out of date. This issue is related to another page.
Closing this issue for now. Hopefully we'll get to update all the related pages before too long.
