### ISSUE TITLE
[workshop outline] omit from TOC

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-develop-training#4]
When https://github.com/w3c/wai-website/issues/60 is available,

Then omit:
* Day 1 schedule
* Day 2 schedule
* Day 3 schedule
* Additional notes for presenters for the technical sessions on days 2 and 3

**Leave**:
* Overall learning objectives
* the sessions

**Comment by yatil** [comment]
See here for example: https://github.com/w3c/wai-develop-training/commit/cc8ac6b01fecc86699843071fda61b397dbf8f9d
