### ISSUE TITLE
[workshop outline] delete WCAG resources where tutorial covers them?

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-develop-training#6]
The previews resource linked to WCAG understanding docs & techniques. Now we have tutorials for some of the topics. The tutorials present the info better, and include the WCAG links.

I added links to the tutorials.

For topics where the tutorials cover all the WCAG links, should we only link to the tutorial, and delete the WCAG links? If so, we probably want to note that so that people know that the WCAG links are in the tutorials.

**Comment by yatil** [comment]
Some people want to go directly to the spec, so I’m ok to leave them here even if a tutorial link is present. This also adds consistency to the document.

**Comment by slhenry** [comment]
Closing issue.. Feel free to re-open if wanted.
